version: '3'

services:

  selenium:
    #image: selenium/standalone-chrome
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2g
  cucumber:
    build: 
      context: .
      dockerfile: Dockerfile
    image: nafreire/apptest:0.0.1
    volumes:
      - .:/apptest
    environment:
      CHROME_HOSTNAME: selenium
    command: cucumber --format pretty --format html --out=results/report.html
    depends_on:
      - selenium

